[package]
name = "{{project-name}}"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.102", features = ["backtrace"] }
axum = { version = "0.8.9" }
maud = "0.27.0"
tokio = { version = "1.52.2", features = ["full"] }
tower-http = { version = "0.6.10", features = ["fs"] }
tracing = { version = "0.1.44", features = ["async-await"] }
tracing-subscriber = "0.3.23"
